site_title: BfROpenLab
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: German Federal Institute for Risk Assessment
# this appears in the footer

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4005
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

defaults:
-
  scope:
    path: ""
    type: "pages"
  values:
    layout: "page"
