<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="data" nsURI="http:///de/bund/bfr/knime/pmmlite/core/data.ecore"
    nsPrefix="de.bund.bfr.knime.pmmlite.core.data">
  <eClassifiers xsi:type="ecore:EClass" name="TimeSeries" eSuperTypes="common.ecore#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="points" upperBound="-1"
        eType="#//TimeSeriesPoint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" upperBound="-1"
        eType="#//Condition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="organism" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matrix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeUnit" eType="ecore:EDataType common.ecore#//Unit"
        defaultValueLiteral="NO_TRANSFORM(NO_UNIT)"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="concentrationUnit" eType="ecore:EDataType common.ecore#//Unit"
        defaultValueLiteral="NO_TRANSFORM(NO_UNIT)"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeSeriesPoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="concentration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" eSuperTypes="common.ecore#//NameableWithUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
  </eClassifiers>
</ecore:EPackage>
