<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="models" nsURI="http:///de/bund/bfr/knime/pmmlite/core/models.ecore"
    nsPrefix="de.bund.bfr.knime.pmmlite.core.models">
  <eClassifiers xsi:type="ecore:EClass" name="Model" abstract="true" interface="true"
      eSuperTypes="common.ecore#//Identifiable">
    <eOperations name="getFormula" eType="#//ModelFormula"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rmse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="r2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="degreesOfFreedom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableRanges" upperBound="-1"
        eType="#//StringToVariableRangeMapEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paramValues" upperBound="-1"
        eType="#//StringToParameterValueMapEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignments" upperBound="-1"
        eType="#//StringToStringMapEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelFormula" abstract="true" interface="true"
      eSuperTypes="common.ecore#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="depVar" eType="#//Variable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="common.ecore#//NameableWithUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableRange">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="common.ecore#//Nameable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="error" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="t" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="p" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="correlations" upperBound="-1"
        eType="#//StringToDoubleMapEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimaryModel" eSuperTypes="#//Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="formula" eType="#//PrimaryModelFormula"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" eType="ecore:EClass data.ecore#//TimeSeries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecondaryModel" eSuperTypes="#//Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="formula" eType="#//SecondaryModelFormula"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" upperBound="-1" eType="#//PrimaryModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TertiaryModel" eSuperTypes="#//Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="formula" eType="#//TertiaryModelFormula"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" upperBound="-1" eType="ecore:EClass data.ecore#//TimeSeries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimaryModelFormula" eSuperTypes="#//ModelFormula">
    <eStructuralFeatures xsi:type="ecore:EReference" name="indepVar" eType="#//Variable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialParam" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecondaryModelFormula" eSuperTypes="#//ModelFormula">
    <eStructuralFeatures xsi:type="ecore:EReference" name="indepVars" upperBound="-1"
        eType="#//Variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transformation" eType="ecore:EDataType common.ecore#//Transform"
        defaultValueLiteral="NO_TRANSFORM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TertiaryModelFormula" eSuperTypes="#//ModelFormula">
    <eStructuralFeatures xsi:type="ecore:EReference" name="indepVars" upperBound="-1"
        eType="#//Variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeVar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialParam" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primaryFormula" eType="#//PrimaryModelFormula"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="secondaryFormulas" upperBound="-1"
        eType="#//SecondaryModelFormula"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="secondaryRenamings" upperBound="-1"
        eType="#//StringToRenamingsMapEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignments" upperBound="-1"
        eType="#//StringToStringMapEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Renamings">
    <eStructuralFeatures xsi:type="ecore:EReference" name="map" upperBound="-1" eType="#//StringToStringMapEntry"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringToStringMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringToDoubleMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringToVariableRangeMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//VariableRange"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringToParameterValueMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ParameterValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringToRenamingsMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Renamings"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
